name: Publish Helm Chart
on:
  release:
    types: [published]

jobs:
  ci_tests:
    uses: ./.github/workflows/test.yml

  publish:
    name: Publish on registry
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Update version
        shell: bash
        run: |
          sed -i 's/0.0.0/${{ github.ref_name }}/' charts/common/Chart.yaml

      - name: Helm Publish
        uses: huggingface/helm-publish-action@latest
        with:
          workingDirectory: charts/common
          tailscaleKey: ${{ secrets.TAILSCALE_AUTHKEY }}
          repository: https://registry.internal.huggingface.tech/chartrepo/charts
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
