name: Publish Helm Chart
on:
  push:
    branches:
      - 'main'
    paths: "charts/**"
  release:
    types: [published]

jobs:
  test:
    uses: ./.github/workflows/test.yml

  publish:
    name: Publish on registry
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2

      - name: Copy readme file
        shell: bash
        run: |
          cp README.md charts/common/README.md

      - name: Update version with release version
        if: github.event_name == 'release' && github.event.action == 'published'
        shell: bash
        env:
          REF_NAME: ${{ github.ref_name }}
        run: |
          sed -i "s/0.0.0/${REF_NAME}/" charts/common/Chart.yaml

      - name: Update version with latest version
        if: (github.event_name == 'release' && github.event.action == 'published') == false
        shell: bash
        run: |
          sed -i 's/0.0.0/0.0.0-latest/' charts/common/Chart.yaml

      - name: Publish on public registry
        shell: bash
        env:
          GH_USERNAME: ${{ secrets.GH_USERNAME }}
          GH_PASSWORD: ${{ secrets.GH_PASSWORD }}
        run: |
          helm package charts/common
          echo "${GH_PASSWORD}" | helm registry login ghcr.io/huggingface/helm-common --username "${GH_USERNAME}" --password-stdin
          helm push common-*.tgz oci://ghcr.io/huggingface/helm-common