name: Unit Tests
on:
  pull_request:
  workflow_call:
  workflow_dispatch:

concurrency:
  group: run-tests-group-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  test:
    permissions:
      contents: read
    name: Unit Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: charts/unit-tests
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Install Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
          helm plugin install https://github.com/quintush/helm-unittest

      - name: Update dependencies
        run: |
          helm dependencies update

      - name: Execute tests
        run: |
          helm unittest -3 .
